import { readFileSync, readdirSync, statSync } from "node:fs"
import { dirname, join, resolve } from "node:path"
import { fileURLToPath } from "node:url"
import { describe, expect, it } from "vitest"

const thisDir = dirname(fileURLToPath(import.meta.url))
const packageRoot = resolve(thisDir, "../..")

function listComponentCss(): string[] {
  const componentsDir = resolve(packageRoot, "src/components")
  const out: string[] = []
  for (const entry of readdirSync(componentsDir)) {
    const full = join(componentsDir, entry)
    if (!statSync(full).isDirectory()) continue
    for (const file of readdirSync(full)) {
      if (/^[a-z][a-z0-9-]*\.css$/.test(file)) {
        out.push(`../components/${entry}/${file}`)
      }
    }
  }
  return out.sort()
}

describe("component CSS imports", () => {
  it("every component <name>.css is referenced from theme.css", () => {
    const themeCss = readFileSync(
      resolve(packageRoot, "src/styles/theme.css"),
      "utf8",
    )
    const startMarker =
      "/* >>> AUTOGENERATED COMPONENT IMPORTS — DO NOT EDIT MANUALLY <<< */"
    const endMarker = "/* >>> END AUTOGENERATED COMPONENT IMPORTS <<< */"
    const start = themeCss.indexOf(startMarker)
    const end = themeCss.indexOf(endMarker)
    expect(start).toBeGreaterThan(-1)
    expect(end).toBeGreaterThan(start)
    const block = themeCss.slice(start, end)

    for (const rel of listComponentCss()) {
      expect(block).toContain(`@import "${rel}";`)
    }
  })
})
