export { defaultLabels } from "./defaults"
export { mergeLabels } from "./mergeLabels"
export { UiLabelsProvider } from "./context"
export { useUiLabels } from "./useUiLabels"
export type { UiLabels, ThemeAxisName, DeepPartialLabels } from "./types"
