import { readFileSync, readdirSync, statSync, writeFileSync } from "node:fs"
import { dirname, join, resolve } from "node:path"
import { fileURLToPath } from "node:url"

const thisFile = fileURLToPath(import.meta.url)
const packageRoot = resolve(dirname(thisFile), "..")
const componentsDir = resolve(packageRoot, "src/components")
const themePath = resolve(packageRoot, "src/styles/theme.css")
const startMarker =
  "/* >>> AUTOGENERATED COMPONENT IMPORTS — DO NOT EDIT MANUALLY <<< */"
const endMarker = "/* >>> END AUTOGENERATED COMPONENT IMPORTS <<< */"

function listImports(): string[] {
  const out: string[] = []
  for (const entry of readdirSync(componentsDir).sort()) {
    const full = join(componentsDir, entry)
    if (!statSync(full).isDirectory()) continue
    for (const file of readdirSync(full).sort()) {
      if (/^[a-z][a-z0-9-]*\.css$/.test(file)) {
        out.push(`@import "../components/${entry}/${file}";`)
      }
    }
  }
  return out
}

function main() {
  const theme = readFileSync(themePath, "utf8")
  const start = theme.indexOf(startMarker)
  const end = theme.indexOf(endMarker)
  if (start < 0 || end < start) {
    throw new Error(`Markers not found in ${themePath}`)
  }
  const imports = listImports()
  const before = theme.slice(0, start + startMarker.length)
  const after = theme.slice(end)
  const block = imports.length ? "\n" + imports.join("\n") + "\n" : "\n"
  const next = before + block + after
  if (next !== theme) {
    writeFileSync(themePath, next)
    console.log(
      `[generate-component-imports] updated ${imports.length} imports`,
    )
  } else {
    console.log("[generate-component-imports] no change")
  }
}

main()
