export {
  ImageEditor,
  ImageEditorRootProvider,
  ImageEditorContext,
  ImageEditorViewport,
  ImageEditorImage,
  ImageEditorSelection,
  ImageEditorHandle,
  ImageEditorGrid,
  ImageEditorAdjustPanel,
  ImageEditorAdjust,
  ImageEditorAdjustClear,
  ImageEditorPanel,
  ImageEditorPresets,
  ImageEditorPreset,
  ImageEditorTools,
  ImageEditorTool,
  ImageEditorRotationSlider,
  ImageEditorAnnotationLayer,
  ImageEditorAnnotationToolbar,
  ImageEditorAnnotationKind,
  ImageEditorAnnotationColor,
  ImageEditorAnnotationWidth,
  ImageEditorAnnotationClear,
  ImageEditorFreeform,
  ImageEditorFreeformClear,
  ImageEditorPerspectiveOverlay,
  ImageEditorPerspectiveReset,
  ImageEditorExtension,
  ImageEditorStatusBar,
  ImageEditorUndo,
  ImageEditorRedo,
  type ImageEditorProps,
  type ImageEditorRootProviderProps,
  type ImageEditorContextProps,
  type ImageEditorAdjustProps,
  type ImageEditorAdjustPanelProps,
  type ImageEditorAdjustClearProps,
  type ImageEditorPanelProps,
  type ImageEditorPresetProps,
  type ImageEditorPresetsProps,
  type ImageEditorToolProps,
  type ImageEditorToolsProps,
  type ImageEditorRotationSliderProps,
  type ImageEditorAnnotationKindProps,
  type ImageEditorAnnotationColorProps,
  type ImageEditorAnnotationWidthProps,
  type ImageEditorAnnotationClearProps,
  type ImageEditorAnnotationToolbarProps,
  type ImageEditorFreeformProps,
  type ImageEditorFreeformClearProps,
  type ImageEditorPerspectiveOverlayProps,
  type ImageEditorPerspectiveResetProps,
  type ImageEditorExtensionProps,
  type ImageEditorStatusBarItem,
  type ImageEditorStatusBarProps,
  type ImageEditorUndoProps,
  type ImageEditorRedoProps,
} from "./ImageEditor"
export { useImageEditorContext } from "./useImageEditorContext"
export { drawStroke } from "./annotationDraw"
export { computeAffine, drawPerspectiveQuad } from "./perspectiveDraw"

// Re-exports from image-common — these don't depend on either compound,
// but consumers that import from the editor package shouldn't have to know
// where the underlying module lives.
export {
  ImageDropzone,
  readFileAsDataURL,
  type ImageDropzoneProps,
  type FileAcceptDetails,
  type FileRejectDetails,
} from "@components/image-common"
export { useImageEditor } from "./useImageEditor"
export type {
  UseImageEditorOptions,
  UseImageEditorReturn,
} from "./useImageEditor"
export {
  DEFAULT_PRESETS,
  FILTER_RANGES,
  NEUTRAL_FILTERS,
  type AnnotationKind,
  type AnnotationStroke,
  type AnnotationsChangeDetails,
  type EditorSnapshot,
  type EditorTool,
  type ExtensionHandler,
  type ExtensionInput,
  type ExtensionOutput,
  type FilterPreset,
  type FilterRange,
  type FilterState,
  type FiltersChangeDetails,
  type FreeformPath,
  type FreeformPathChangeDetails,
  type PerspectiveChangeDetails,
  type PerspectiveCorners,
  type Point,
  type ToolChangeDetails,
} from "./types"
